name: 'ReformCloudBukkitPermissions'
version: '3'
authors: [ 'derklaro', 'ReformCloud-Team' ]
main: systems.reformcloud.permissions.bukkit.BukkitPermissionPlugin
api-version: '1.13'
depend:
  - ReformCloudSpigotExecutor

softdepend:
  - Vault
  - VaultAPI

# Additional
website: 'https://reformcloud.systems'
description: 'The reformcloud permission plugin'
