name: ReformCloud2Signs
version: "2.0"
author: derklaro
main: systems.reformcloud.reformcloud2.signs.bukkit.BukkitPlugin

depend:
  - ReformCloud2SpigotExecutor

# Additional
website: "https://reformcloud.systems"
description: "The reformcloud sign plugin"

commands:
  signs:
