name: 'ReformCloud2SpigotExecutor'
version: '2'
authors: ['derklaro', 'ReformCloud-Team']
main: systems.refomcloud.reformcloud2.embedded.plugin.spigot.SpigotLauncher
api-version: '1.13'

load: STARTUP
# Additional
website: 'https://reformcloud.systems'
description: 'The reformcloud executor api'
