name: 'ReformCloud2SpigotExecutor'
version: '2'
authors: ['derklaro', 'ReformCloud-Team']
main: systems.reformcloud.reformcloud2.executor.api.spigot.SpigotLauncher

load: STARTUP
# Additional
website: 'https://reformcloud.systems'
description: 'The reformcloud executor api'
