name: Java CI

on:
  push:
    branches:
      - stable
      - indev
  pull_request:
    branches:
      - stable
      - indev

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -V clean package --file pom.xml
